namespace Game.Server.Packets
{
	public enum ConsortiaPackageType
	{
		BOSS_OPEN_CLOSE = 0x1F,
		BUY_BADGE = 28,
		CONSORTIA_APPLY_STATE = 7,
		CONSORTIA_BANCHAT_UPDATE = 0x10,
		CONSORTIA_BOSS_INFO = 30,
		CONSORTIA_CREATE = 1,
		CONSORTIA_CHAIRMAN_CHAHGE = 19,
		CONSORTIA_CHAT = 20,
		CONSORTIA_DESCRIPTION_UPDATE = 14,
		CONSORTIA_DISBAND = 2,
		CONSORTIA_DUTY_DELETE = 9,
		CONSORTIA_DUTY_UPDATE = 10,
		CONSORTIA_EQUIP_CONTROL = 24,
		CONSORTIA_INVITE = 11,
		CONSORTIA_INVITE_DELETE = 13,
		CONSORTIA_INVITE_PASS = 12,
		CONSORTIA_LEVEL_UP = 21,
		CONSORTIA_PLACARD_UPDATE = 0xF,
		CONSORTIA_RENEGADE = 3,
		CONSORTIA_RICHES_OFFER = 6,
		CONSORTIA_TASK_RELEASE = 22,
		CONSORTIA_TRYIN = 0,
		CONSORTIA_TRYIN_DEL = 5,
		CONSORTIA_TRYIN_PASS = 4,
		CONSORTIA_USER_GRADE_UPDATE = 18,
		CONSORTIA_USER_REMARK_UPDATE = 17,
		CONSORTION_MAIL = 29,
		DONATE = 23,
		POLL_CANDIDATE = 25,
		SKILL_SOCKET = 26
	}
}
