namespace Game.Server.Packets
{
	public enum NoviceActiveType
	{
		/*GRADE_UP_ACTIVE = 1,
		RECHANGE_MONEY_ACTIVE = 4,
		STRENGTHEN_WEAPON_ACTIVE = 2,
		UPGRADE_VIP_ACTIVE = 5,
		UPDATE_FIGHTPOWER = 6,
		RECHARGE_SPECIAL = 7,
		USE_MONEY_SPECIAL = 8,
		USE_MONEY_ACTIVE = 3*/
		TANG_CAP_VIP = 1,
		TIEUXU_TICHLUY = 2,
		NAPXU_TICHLUY = 3,
		TIEUXU_DACBIET = 4,
		NAPXU_DACBIET = 5
	}
}
