namespace Game.Server.Packets
{
	public enum PetPackageType
	{
		UPDATE_PET = 1,
		ADD_PET = 2,
		MOVE_PETBAG = 3,
		FEED_PET = 4,
		REFRESH_PET = 5,
		ADOPT_PET = 6,
		EQUIP_PET_SKILL = 7,
		RELEASE_PET = 8,
		RENAME_PET = 9,
		PAY_SKILL = 0x10,
		FIGHT_PET = 17,
		REVER_PET = 18,
		ADD_PET_EQUIP = 20,
		DEL_PET_EQUIP = 21,
		PET_RISINGSTAR = 22,
		PET_EVOLUTION = 23,
		PET_FORMINFO = 24,
		PET_FOLLOW = 25,
		PET_BREAK = 0x1F,
		PET_WAKE = 0x20,
		EAT_PETS = 33,
		PET_BREAK_INFO = 34
	}
}
